version: 2
registries:
  composer-repository-packages-webtools-nz:
    type: composer-repository
    url: https://packages.webtools.nz
    username: webtools
    password: "${{secrets.COMPOSER_REPOSITORY_PACKAGES_WEBTOOLS_NZ_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "07:00"
    timezone: Pacific/Auckland
  open-pull-requests-limit: 10
  registries:
  - composer-repository-packages-webtools-nz
